kubernetesClusterDomain: cluster.local
pp2Host:
  ports:
  - name: port-1
    port: 4500
    protocol: UDP
    targetPort: 4500
  - name: port-2
    port: 4500
    protocol: TCP
    targetPort: 4500
  pp2Host:
    image:
      repository: localhost:5000/pp2host
      tag: latest
    imagePullPolicy: Always
  replicas: 1
  type: LoadBalancer
