---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pp2host
  namespace: pp2host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pp2host
  template:
    metadata:
      labels:
        app: pp2host
    spec:
      containers:
      - name: pp2host
        image: localhost:5000/pp2host:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4500
          name: pp2-udp1
          protocol: UDP
        - containerPort: 4500
          name: pp2-tcp1
          protocol: TCP
        volumeMounts:
        - name: pp2host-config
          mountPath: /etc/pp2host
      volumes:
      - name: pp2host-config
        hostPath:
          path: /opt/pp2/pp2host
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pp2host
  name: pp2host
  namespace: pp2host
spec:
  ports:
  - name: port-1
    port: 4500
    protocol: UDP
    targetPort: 4500
  - name: port-2
    port: 4500
    protocol: TCP
    targetPort: 4500
  selector:
    app: pp2host
  type: LoadBalancer
status:
  loadBalancer: {}

