apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-pp2host
  labels:
    app: pp2host
  {{- include "chart.labels" . | nindent 4 }}
  namespace: pp2host
spec:
  type: {{ .Values.pp2Host.type }}
  selector:
    app: pp2host
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.pp2Host.ports | toYaml | nindent 2 -}}
